require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GradeConfigsController do

  # This should return the minimal set of attributes required to create a valid
  # GradeConfig. As you add validations to GradeConfig, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "metricconfig_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GradeConfigsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all grade_configs as @grade_configs" do
      grade_config = GradeConfig.create! valid_attributes
      get :index, {}, valid_session
      assigns(:grade_configs).should eq([grade_config])
    end
  end

  describe "GET show" do
    it "assigns the requested grade_config as @grade_config" do
      grade_config = GradeConfig.create! valid_attributes
      get :show, {:id => grade_config.to_param}, valid_session
      assigns(:grade_config).should eq(grade_config)
    end
  end

  describe "GET new" do
    it "assigns a new grade_config as @grade_config" do
      get :new, {}, valid_session
      assigns(:grade_config).should be_a_new(GradeConfig)
    end
  end

  describe "GET edit" do
    it "assigns the requested grade_config as @grade_config" do
      grade_config = GradeConfig.create! valid_attributes
      get :edit, {:id => grade_config.to_param}, valid_session
      assigns(:grade_config).should eq(grade_config)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GradeConfig" do
        expect {
          post :create, {:grade_config => valid_attributes}, valid_session
        }.to change(GradeConfig, :count).by(1)
      end

      it "assigns a newly created grade_config as @grade_config" do
        post :create, {:grade_config => valid_attributes}, valid_session
        assigns(:grade_config).should be_a(GradeConfig)
        assigns(:grade_config).should be_persisted
      end

      it "redirects to the created grade_config" do
        post :create, {:grade_config => valid_attributes}, valid_session
        response.should redirect_to(GradeConfig.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grade_config as @grade_config" do
        # Trigger the behavior that occurs when invalid params are submitted
        GradeConfig.any_instance.stub(:save).and_return(false)
        post :create, {:grade_config => { "metricconfig_id" => "invalid value" }}, valid_session
        assigns(:grade_config).should be_a_new(GradeConfig)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GradeConfig.any_instance.stub(:save).and_return(false)
        post :create, {:grade_config => { "metricconfig_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grade_config" do
        grade_config = GradeConfig.create! valid_attributes
        # Assuming there are no other grade_configs in the database, this
        # specifies that the GradeConfig created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GradeConfig.any_instance.should_receive(:update).with({ "metricconfig_id" => "1" })
        put :update, {:id => grade_config.to_param, :grade_config => { "metricconfig_id" => "1" }}, valid_session
      end

      it "assigns the requested grade_config as @grade_config" do
        grade_config = GradeConfig.create! valid_attributes
        put :update, {:id => grade_config.to_param, :grade_config => valid_attributes}, valid_session
        assigns(:grade_config).should eq(grade_config)
      end

      it "redirects to the grade_config" do
        grade_config = GradeConfig.create! valid_attributes
        put :update, {:id => grade_config.to_param, :grade_config => valid_attributes}, valid_session
        response.should redirect_to(grade_config)
      end
    end

    describe "with invalid params" do
      it "assigns the grade_config as @grade_config" do
        grade_config = GradeConfig.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GradeConfig.any_instance.stub(:save).and_return(false)
        put :update, {:id => grade_config.to_param, :grade_config => { "metricconfig_id" => "invalid value" }}, valid_session
        assigns(:grade_config).should eq(grade_config)
      end

      it "re-renders the 'edit' template" do
        grade_config = GradeConfig.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GradeConfig.any_instance.stub(:save).and_return(false)
        put :update, {:id => grade_config.to_param, :grade_config => { "metricconfig_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grade_config" do
      grade_config = GradeConfig.create! valid_attributes
      expect {
        delete :destroy, {:id => grade_config.to_param}, valid_session
      }.to change(GradeConfig, :count).by(-1)
    end

    it "redirects to the grade_configs list" do
      grade_config = GradeConfig.create! valid_attributes
      delete :destroy, {:id => grade_config.to_param}, valid_session
      response.should redirect_to(grade_configs_url)
    end
  end

end
