require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GradeCalcsController do

  # This should return the minimal set of attributes required to create a valid
  # GradeCalc. As you add validations to GradeCalc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "gradecalc" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GradeCalcsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all grade_calcs as @grade_calcs" do
      grade_calc = GradeCalc.create! valid_attributes
      get :index, {}, valid_session
      assigns(:grade_calcs).should eq([grade_calc])
    end
  end

  describe "GET show" do
    it "assigns the requested grade_calc as @grade_calc" do
      grade_calc = GradeCalc.create! valid_attributes
      get :show, {:id => grade_calc.to_param}, valid_session
      assigns(:grade_calc).should eq(grade_calc)
    end
  end

  describe "GET new" do
    it "assigns a new grade_calc as @grade_calc" do
      get :new, {}, valid_session
      assigns(:grade_calc).should be_a_new(GradeCalc)
    end
  end

  describe "GET edit" do
    it "assigns the requested grade_calc as @grade_calc" do
      grade_calc = GradeCalc.create! valid_attributes
      get :edit, {:id => grade_calc.to_param}, valid_session
      assigns(:grade_calc).should eq(grade_calc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GradeCalc" do
        expect {
          post :create, {:grade_calc => valid_attributes}, valid_session
        }.to change(GradeCalc, :count).by(1)
      end

      it "assigns a newly created grade_calc as @grade_calc" do
        post :create, {:grade_calc => valid_attributes}, valid_session
        assigns(:grade_calc).should be_a(GradeCalc)
        assigns(:grade_calc).should be_persisted
      end

      it "redirects to the created grade_calc" do
        post :create, {:grade_calc => valid_attributes}, valid_session
        response.should redirect_to(GradeCalc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grade_calc as @grade_calc" do
        # Trigger the behavior that occurs when invalid params are submitted
        GradeCalc.any_instance.stub(:save).and_return(false)
        post :create, {:grade_calc => { "gradecalc" => "invalid value" }}, valid_session
        assigns(:grade_calc).should be_a_new(GradeCalc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GradeCalc.any_instance.stub(:save).and_return(false)
        post :create, {:grade_calc => { "gradecalc" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grade_calc" do
        grade_calc = GradeCalc.create! valid_attributes
        # Assuming there are no other grade_calcs in the database, this
        # specifies that the GradeCalc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GradeCalc.any_instance.should_receive(:update).with({ "gradecalc" => "MyString" })
        put :update, {:id => grade_calc.to_param, :grade_calc => { "gradecalc" => "MyString" }}, valid_session
      end

      it "assigns the requested grade_calc as @grade_calc" do
        grade_calc = GradeCalc.create! valid_attributes
        put :update, {:id => grade_calc.to_param, :grade_calc => valid_attributes}, valid_session
        assigns(:grade_calc).should eq(grade_calc)
      end

      it "redirects to the grade_calc" do
        grade_calc = GradeCalc.create! valid_attributes
        put :update, {:id => grade_calc.to_param, :grade_calc => valid_attributes}, valid_session
        response.should redirect_to(grade_calc)
      end
    end

    describe "with invalid params" do
      it "assigns the grade_calc as @grade_calc" do
        grade_calc = GradeCalc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GradeCalc.any_instance.stub(:save).and_return(false)
        put :update, {:id => grade_calc.to_param, :grade_calc => { "gradecalc" => "invalid value" }}, valid_session
        assigns(:grade_calc).should eq(grade_calc)
      end

      it "re-renders the 'edit' template" do
        grade_calc = GradeCalc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GradeCalc.any_instance.stub(:save).and_return(false)
        put :update, {:id => grade_calc.to_param, :grade_calc => { "gradecalc" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grade_calc" do
      grade_calc = GradeCalc.create! valid_attributes
      expect {
        delete :destroy, {:id => grade_calc.to_param}, valid_session
      }.to change(GradeCalc, :count).by(-1)
    end

    it "redirects to the grade_calcs list" do
      grade_calc = GradeCalc.create! valid_attributes
      delete :destroy, {:id => grade_calc.to_param}, valid_session
      response.should redirect_to(grade_calcs_url)
    end
  end

end
