require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MetricconfigsController do

  # This should return the minimal set of attributes required to create a valid
  # Metricconfig. As you add validations to Metricconfig, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MetricconfigsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all metricconfigs as @metricconfigs" do
      metricconfig = Metricconfig.create! valid_attributes
      get :index, {}, valid_session
      assigns(:metricconfigs).should eq([metricconfig])
    end
  end

  describe "GET show" do
    it "assigns the requested metricconfig as @metricconfig" do
      metricconfig = Metricconfig.create! valid_attributes
      get :show, {:id => metricconfig.to_param}, valid_session
      assigns(:metricconfig).should eq(metricconfig)
    end
  end

  describe "GET new" do
    it "assigns a new metricconfig as @metricconfig" do
      get :new, {}, valid_session
      assigns(:metricconfig).should be_a_new(Metricconfig)
    end
  end

  describe "GET edit" do
    it "assigns the requested metricconfig as @metricconfig" do
      metricconfig = Metricconfig.create! valid_attributes
      get :edit, {:id => metricconfig.to_param}, valid_session
      assigns(:metricconfig).should eq(metricconfig)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Metricconfig" do
        expect {
          post :create, {:metricconfig => valid_attributes}, valid_session
        }.to change(Metricconfig, :count).by(1)
      end

      it "assigns a newly created metricconfig as @metricconfig" do
        post :create, {:metricconfig => valid_attributes}, valid_session
        assigns(:metricconfig).should be_a(Metricconfig)
        assigns(:metricconfig).should be_persisted
      end

      it "redirects to the created metricconfig" do
        post :create, {:metricconfig => valid_attributes}, valid_session
        response.should redirect_to(Metricconfig.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved metricconfig as @metricconfig" do
        # Trigger the behavior that occurs when invalid params are submitted
        Metricconfig.any_instance.stub(:save).and_return(false)
        post :create, {:metricconfig => {  }}, valid_session
        assigns(:metricconfig).should be_a_new(Metricconfig)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Metricconfig.any_instance.stub(:save).and_return(false)
        post :create, {:metricconfig => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested metricconfig" do
        metricconfig = Metricconfig.create! valid_attributes
        # Assuming there are no other metricconfigs in the database, this
        # specifies that the Metricconfig created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Metricconfig.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => metricconfig.to_param, :metricconfig => { "these" => "params" }}, valid_session
      end

      it "assigns the requested metricconfig as @metricconfig" do
        metricconfig = Metricconfig.create! valid_attributes
        put :update, {:id => metricconfig.to_param, :metricconfig => valid_attributes}, valid_session
        assigns(:metricconfig).should eq(metricconfig)
      end

      it "redirects to the metricconfig" do
        metricconfig = Metricconfig.create! valid_attributes
        put :update, {:id => metricconfig.to_param, :metricconfig => valid_attributes}, valid_session
        response.should redirect_to(metricconfig)
      end
    end

    describe "with invalid params" do
      it "assigns the metricconfig as @metricconfig" do
        metricconfig = Metricconfig.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Metricconfig.any_instance.stub(:save).and_return(false)
        put :update, {:id => metricconfig.to_param, :metricconfig => {  }}, valid_session
        assigns(:metricconfig).should eq(metricconfig)
      end

      it "re-renders the 'edit' template" do
        metricconfig = Metricconfig.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Metricconfig.any_instance.stub(:save).and_return(false)
        put :update, {:id => metricconfig.to_param, :metricconfig => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested metricconfig" do
      metricconfig = Metricconfig.create! valid_attributes
      expect {
        delete :destroy, {:id => metricconfig.to_param}, valid_session
      }.to change(Metricconfig, :count).by(-1)
    end

    it "redirects to the metricconfigs list" do
      metricconfig = Metricconfig.create! valid_attributes
      delete :destroy, {:id => metricconfig.to_param}, valid_session
      response.should redirect_to(metricconfigs_url)
    end
  end

end
